apiVersion: batch/v1
kind: Job
metadata:
  name: wbcm-webapp-job
spec:
  template:
    spec:
      containers:
      - name: wbcm-webapp-job
        image: yash5090/wbcm-webapp:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
